### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by pmiess** [0install/feedlint#5]
`0install run http://0install.net/2007/interfaces/FeedLint.xml -d awka.xml
Checking /home/pmiess/projects/my.apps.0install.net/devel/awka.xmlTraceback (most recent call last):
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_N5GGEFDYS6ZU6VJDJ2R7EZ5RHCHGCBSCPPIPWGYMZ3E335A4WYAQ/feedlint", line 298, in <module>
    check_gpg_sig(dom.attrs['uri'], stream)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_N5GGEFDYS6ZU6VJDJ2R7EZ5RHCHGCBSCPPIPWGYMZ3E335A4WYAQ/feedlint", line 247, in check_gpg_sig
    result('Fetched')
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_N5GGEFDYS6ZU6VJDJ2R7EZ5RHCHGCBSCPPIPWGYMZ3E335A4WYAQ/display.py", line 45, in result
    msg = highlight(msg, colour)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_N5GGEFDYS6ZU6VJDJ2R7EZ5RHCHGCBSCPPIPWGYMZ3E335A4WYAQ/display.py", line 59, in highlight
    return curses.tparm(set_fg, COLOURS[colour]) + msg + curses.tparm(normal)
TypeError: can't concat str to bytes
`

`0install select http://0install.net/2007/interfaces/FeedLint.xml
- URI: http://0install.net/2007/interfaces/FeedLint.xml
  Version: 0.10
  Path: /home/pmiess/.cache/0install.net/implementations/sha256new_N5GGEFDYS6ZU6VJDJ2R7EZ5RHCHGCBSCPPIPWGYMZ3E335A4WYAQ

  - URI: https://apps.0install.net/python/python.xml
    Version: 3.7.6
    Path: (package:gentoo:dev-lang/python:3.7.6:x86_64)

  - URI: http://0install.net/2007/interfaces/ZeroInstall.xml
    Version: 2.3.12
    Path: /home/pmiess/.cache/0install.net/implementations/sha256new_UUKHJE54V5UDDL2EIMWO5PLH7R6OG7IHEWRPQMJVNPDN5CKRN4OA

    - URI: https://apps.0install.net/utils/gnupg.xml
      Version: 2.2.17
      Path: (package:gentoo:app-crypt/gnupg:2.2.17:x86_64)
`

running with 0install 2.3.11

**Comment by talex5** [comment]
Does #6 fix it for you?

**Comment by pmiess** [comment]
yes that fixes it
