### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

### ISSUE THREAD

**Issue by pmiess** [0install/feedlint#7]
if you run Feedlint on a feed you get the following error
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/distro.py", line 29, in _set_quick_test
    impl.quick_test_mtime = int(os.stat(path).st_mtim
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

stack trace
```
feedlint mupdf.xml
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/0install", line 14, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/zeroinstall/cmd/__init__.py", line 381, in main
    cmd.handle(config, options, args)
  File "/usr/lib/python3.7/site-packages/zeroinstall/cmd/run.py", line 38, in handle
    sels = app.get_selections(may_update = True, use_gui = options.gui)
  File "/usr/lib/python3.7/site-packages/zeroinstall/apps.py", line 166, in get_selections
    sels = self._check_for_updates(sels, use_gui)
  File "/usr/lib/python3.7/site-packages/zeroinstall/apps.py", line 279, in _check_for_updates
    unavailable_selections = sels.get_unavailable_selections(config = self.config, include_packages = True)
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/selections.py", line 394, in get_unavailable_selections
    return [sel for sel in self.selections.values() if needs_download(sel)]
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/selections.py", line 394, in <listcomp>
    return [sel for sel in self.selections.values() if needs_download(sel)]
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/selections.py", line 385, in needs_download
    feed = iface_cache.get_feed(sel.feed)
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/iface_cache.py", line 367, in get_feed
    feed = self.distro.get_feed(master_feed)
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/distro.py", line 265, in get_feed
    _set_quick_test(impl, gobject.__path__)	        # Python 3
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/distro.py", line 29, in _set_quick_test
    impl.quick_test_mtime = int(os.stat(path).st_mtime)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

**Comment by bastianeicher** [comment]
I successfully ran this on Ubuntu 20.04 (with Python 3.8.6).

@pmiess
Which Linux distro are you running?
Could you post the output of `0install select --version-for http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.13 http://0install.net/2007/interfaces/FeedLint.xml`?

@talex5
I'm not really familiar with the Python curses module.
Should this:
https://github.com/0install/feedlint/blob/edcd68560bd4de913fa846b9725b7308501319eb/display.py#L57-L61
perhaps be changed to:
```python
def highlight(msg, colour): # returns str
	if set_fg and normal:
		return curses.tparm(set_fg, COLOURS[colour]).decode('UTF-8') + msg + curses.tparm(normal).decode('UTF-8')
	else:
		return msg
```
or:
```python
def highlight(msg, colour): # returns bytes
	if set_fg and normal:
		return curses.tparm(set_fg, COLOURS[colour]) + msg.encode('UTF-8') + curses.tparm(normal)
	else:
		return msg.encode('UTF-8')
```
?

**Comment by pmiess** [comment]
I run Gentoo
```
0install select --version-for http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.13 http://0install.net/2007/interfaces/FeedLint.xml
- URI: http://0install.net/2007/interfaces/FeedLint.xml
  Version: 0.10
  Path: /home/pmiess/.cache/0install.net/implementations/sha256new_N5GGEFDYS6ZU6VJDJ2R7EZ5RHCHGCBSCPPIPWGYMZ3E335A4WYAQ

  - URI: https://apps.0install.net/python/python.xml
    Version: 3.8.4-1
    Path: (package:gentoo:dev-lang/python:3.8.4-1:x86_64)

  - URI: http://0install.net/2007/interfaces/ZeroInstall.xml
    Version: 2.3.13
    Path: /home/pmiess/.cache/0install.net/implementations/sha256new_IJK75D4MWTFWQADUXCUPY6EAM2DG45UMFJ5Z3BAZPZV5PXT34AYQ

    - URI: https://apps.0install.net/utils/gnupg.xml
      Version: 2.2.25
      Path: (package:gentoo:app-crypt/gnupg:2.2.25:x86_64)
```

**Comment by talex5** [comment]
I've made a new release of feedlint (0.11) with the changes that were already on master. That fixes it for me.

**Comment by pmiess** [comment]
works for me  :D thanks for the fix
